[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.19"
evm_version = "paris"

[fuzz]
runs = 1024

# Remappings are setup using remappings.txt, since forge seems to ignore remappings here

[fmt]
line_length = 100
tab_width = 4
bracket_spacing = false
multiline_func_header = "params_first"
quote_style = "double"
number_underscore = "thousands"
wrap_comments = false
ignore = [
  "lib/**",
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

[dependencies]
forge-std = "1.9.1"
axis-core = { version = "0.5.1", git = "git@github.com:Axis-Fi/axis-core.git", rev = "d07b3311771ea3162d99aa68689e40f4f4bd8135" }
