[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.19"
evm_version = "paris"

[fuzz]
runs = 1024

# Remappings are setup using remappings.txt, since forge seems to ignore remappings here

[fmt]
line_length = 100
tab_width = 4
bracket_spacing = false
multiline_func_header = "params_first"
quote_style = "double"
number_underscore = "thousands"
wrap_comments = false
ignore = [
  "lib/**",
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

[dependencies]
forge-std = "1.9.1"
solmate = { version = "6.7.0", url = "git@github.com:transmissions11/solmate.git", commit = "c892309933b25c03d32b1b0d674df7ae292ba925" }
axis-core = { version = "0.5.1", git = "git@github.com:Axis-Fi/axis-core.git", rev = "d07b3311771ea3162d99aa68689e40f4f4bd8135" }
axis-periphery = { version = "0.5.1", git = "git@github.com:Axis-Fi/axis-periphery.git", rev = "fffb93ada5fe5d6f6529f0030d1c16a623ab4782" }
